#!/bin/bash
# shellcheck disable=SC2094
########################################################
# This one sets an info to a file like a tag or a name #
name="${1}"
shift
while read -r id
do
	loc="${IDX_DIR}"/$(idxpand "${id}")
	
	idxchkloc "${loc}" || continue

	if [[ ! -f "${loc}/${name}" ]]
	then 
		# we dont have to check if there are no tags yet 
		for value in "$@"
		do
			echo "${value}" >> "${loc}/${name}"
		done
	else
		( 
			declare -A temp
			
			output=()

			while read -r s
			do 
				output=("${output[@]}" "${s}")
				((temp["${s}"]++))
			done
			for s in "${@}"
			do
				if [[ -n ${temp["${s}"]} ]]
				then
					continue
				else
					output=("${output[@]}" "${s}")
				fi
			done

			(
				for value in "${output[@]}" 
				do
					echo "${value}"
				done
			) > "${loc}/${name}"
		) < "${loc}/${name}" 
	fi
	echo "${id}"
done

