#!/bin/bash
############################################################
# This one recieves a list of file ids from the repository #
while read id
do
	gen_loc
	if [[ ! -d ${loc} ]]
	then
		errcho "ID ${id} does not exist in index, skipping"
		continue
	fi
	if [[ ! -f ${loc}/data ]]
	then
		errcho "Data of ${id} does not exist in index, skipping"
		continue
	fi
	# now lets find a useable filename and go ahead... 
	if [[ ! -f ${loc}/name ]] 
	then 
		name=${id}
	else
		read name < ${loc}/${name}
	fi
	if [[ -e ${name} ]]
	then
		readlink ${name} | read tloc
		if [[ "${tloc}" = "${loc}/data" ]]
		then
			# nothing left to do, skip it
			continue
		fi 	
		errcho "File ${name} already exist locally skipping"
		continue
	fi
	ln -s ${loc}/data ${name}
	echo ${name}
done

