#!/bin/bash
##############################################
# This one adds a pdf file to the repository #
while read -r file
do
	if [[ ! -f "${file}" ]]
	then
		errcho "File ${file} does not exist skipping"
		continue
	fi
	if [[ -L "${file}" ]]
	then
		link=$(readlink "${file}")
		if [[ "${link}" = ${IDX_BLOB}/*/???????????????????????????????????????????????????????????????? ]]
		then
			id="${link##*/}"
		else
			errcho "File ${file} is a symlink but not pointing to idx store, skipping"
			continue
		fi
	else
		# regular file, not indexed yet 
		id=$(sha256sum -b "${file}")
		id="${id% *}"
	fi
	
	loc="${IDX_DIR}"/$(idxpand "${id}")
	blob="${IDX_BLOB}"/$(idxpand "${id}")

	if [[ -a "${blob}" ]]
	then
		errcho "File ${file} is already indexed updating record"
		if [[ -a "${file}" ]]
		then
			rm -f "${file}"
		fi
		if [[ ! -d "${loc}" ]]
		then
			errcho "File ${file} is already indexed but index missing, creating new ${loc}"
			mkdir -p "${loc}"
		fi
	else
		if [[ -d "${loc}" ]]
		then
			errcho "File ${file} is already indexed but data missing, readd data"
		fi
		mkdir -p "${loc}"
		mkdir -p "${blob%/*}"
		mv "${file}" "${blob}"
		chmod 444 "${blob}"
	fi
	ln -s "${blob}" "${file}"
	# do basename just in case
	file="${file##*/}"
	# save name
	echo "${id}" | idx set name "${file}" > /dev/null
	if [[ ! -f "${loc}/datetime" ]]
	then
		date=$(date '+%Y-%m-%d %H:%M:%S')
		idx datetime set "${date:0:10}" "${date:11:8}" <<< "${id}" > /dev/null
	fi
	if [[ ! -f "${loc}/mimetype" ]]
	then
		file -L -b --mime-type "${blob}" > "${loc}/mimetype"
	fi
	echo "${id}"
done

