#!/bin/bash
########################ä#################################
# This creates a text file right next to a data file for #
# full text pdf search                                   #
##########################################################
while read id
do
	loc="${IDX_DIR}"/$(idxpand ${id})
	blob="${IDX_BLOB}"/$(idxpand ${id})
	
	idxchkloc "${loc}" || continue
	idxchkblob "${blob}" ", skipping" || continue

	read mimetype < "${loc}/mimetype"
	mimetype="${mimetype:="pdf"}"
	if [[ "${mimetype}" = *pdf* ]]
	then 
		pdftotext "${blob}" "${loc}/text"
		echo "${id}"
		continue
	fi
	errcho "unknown mimetype ${mimetype} for id ${id} skipping"
	continue
done

