#!/bin/bash
# shellcheck disable=SC2154
# because I have no idea whatsoever how I should structure that 
# work, I will begin with a spagetti single file code aproach of
# a workflow/menu engine for idx

unset_tag() {
	id="${1}"
	shift
	read -e -p "tags > " -r tags
	# shellcheck disable=SC2086
	echo "${id}" | idx untag ${tags}
	show_info_detail "${id}" tag
}

set_tag() {
	id="${1}"
	shift
	read -e -p "tags > " -r tags
	# shellcheck disable=SC2086
	echo "${id}" | idx tag ${tags}
	show_info_detail "${id}" tag
}

show_info_detail() {
	id="${1}"
	shift
	name="${1}"
	shift
	echo "${id}" | idx info "${name}"
}

show_info_detail_collected() {
	id="${1}"
	shift
	show_info_detail "${id}" name
	show_info_detail "${id}" datetime
	show_info_detail "${id}" mimetype
	show_info_detail "${id}" tag
}

show_info() {
	id="${1}"
	shift
	pos=($(echo "${id}" | idx info | (
		# shellcheck disable=SC2034
		while read -r shortid info garbage
		do
			echo "${info}"
		done
	)))
	select item in ".." "${pos[@]}"
	do
		if [[ "${item}" = ".." ]]
		then 
			return
		fi
		if [[ -n "${item}" ]]
		then 
			show_info_detail "${id}" "${item}"
		fi
	done
}

edit_doc() {
	doc="${1}"
	shift
	id=$(echo "${doc}" | idx file2id)
	declare -A edit_doc_menu
	edit_doc_menu["Show Document"]="atril ${doc}"
	edit_doc_menu["Show Info"]="show_info ${id}"
	edit_doc_menu["Show Info Collection"]="show_info_detail_collected ${id}"
	edit_doc_menu["Set a Tag"]="set_tag ${id}"
	edit_doc_menu["Delete a Tag"]="unset_tag ${id}"
	while true
	do 
		select item in ".." "${!edit_doc_menu[@]}"
		do
			if [[ "${item}" = ".." ]]
			then 
				return
			fi
			if [[ -z "${item}" ]] 
			then
				break
			fi
			if [[ -n ${edit_doc_menu["${item}"]} ]]
			then 
				${edit_doc_menu["${item}"]}
				break
			fi
		done
	done
}

select_docs() {
	docs=()
	for file in *
	do
		if [[ ! -f "${file}" ]]
		then
			continue
		fi
		if [[ -L "${file}" ]]
		then
			link=$(readlink "${file}")
			if [[ "${link}" = ${IDX_BLOB}/*/???????????????????????????????????????????????????????????????? ]]
			then
				# we have an indexed document here, this is what we want 
				docs+=("${file}")
			fi
		fi
	done
	select doc in ".." "${docs[@]}"
	do
		if [[ "${doc}" = ".." ]]
		then 
			return
		fi
		if [[ -n "${doc}" ]]
		then 
			edit_doc "${doc}"
		fi
	done
}

select_docs


