#!/bin/bash
########################################################
# This one sets an info to a file like a tag or a name #
filter_regex="false"
invert_match="false"
while [[ "${1}" = -* ]] && [[ -n "${1}" ]]
do
	if [[ ${1} == "-v" ]]
	then
		invert_match="true"
		shift
		continue
	fi
	if [[ ${1} == "-e" ]]
	then
		filter_regex="true"
		shift
		continue
	fi
	errcho "I dont understand parameter ${1}"
	shift
	continue
done
name=${1}
shift
while read -r id
do
	loc="${IDX_DIR}"/$(idxpand "${id}")
	
	idxchkloc "${loc}" || continue

	if [[ ! -f ${loc}/${name} ]]
	then 
		# we dont have to check if there are no tags 
		continue
	else
		( 
			declare -A temp
			
			if [[ "${filter_regex}" = "true" ]]
			then 
				# we have to compare bit by bit 
				# if we do filtering 
				while read -r s
				do 
					for p in "${@}"
					do
						# shellcheck disable=SC2053
						if [[ "${s}" = ${p} ]]
						then
							if [[ "${invert_match}" = "false" ]]
							then
								echo "${id}"
							fi
							exit
						fi
					done
				done

			else
				# filter non regex implementation 
				for s in "${@}"
				do
					((temp["${s}"]++))
				done
				
				while read -r s
				do 
					if [[ -n "${temp[${s}]}" ]]
					then
						if [[ "${invert_match}" = "false" ]]
						then
							echo "${id}"
						fi 
						exit
					fi
				done
			fi
			if [[ "${invert_match}" = "true" ]]
			then
				echo "${id}"
			fi 
		) < "${loc}/${name}" 
	fi
done

