#!/bin/bash
# shellcheck disable=SC2094
############################################################
# This one recieves a list of file ids from the repository #
while [[ "${1}" = -* ]] && [[ -n "${1}" ]]
do
	if [[ "${1}" = "-t" ]]
	then
		shift
		target="${1}"
		shift
		if [[ ! -d "${target}" ]]
		then
			mkdir -p "${target}"
		fi
		cd "${target}" || exit $?
		continue
	fi
	errcho "I dont understand parameter ${1}"
	shift
	continue
done

while read -r id
do
	loc="${IDX_DIR}"/$(idxpand "${id}")
	blob="${IDX_BLOB}"/$(idxpand "${id}")
	
	idxchkloc "${loc}" || continue
	idxchkblob "${blob}" ", skipping" || continue

	# now lets find a useable filename and go ahead...
	if [[ ! -f "${loc}/name" ]] 
	then 
		name="${id}"
		# we guess here that it is unlikely that a symlink known exactly as the id is in the 
		# directory pointing to something else than the idxed data blob 
		while [[ -e "${name}" ]]
		do
			if [[ -L "${name}" ]]
			then
				tloc=$(readlink "${name}")
				if [[ "${tloc}" = "${blob}" ]]
				then
					# nothing left to do, skip it
					break
				fi 	
			fi
			cnt=$((cnt+1))
			name="${cnt}-${name#*-}"
		done
	else
		name=$(
			(while read -r name
			do
				if [[ ! -e "${name}" ]]
				then
					echo "${name}"
					exit
				fi
				if [[ -L "${name}" ]]
				then
					tloc=$(readlink "${name}")
					if [[ "${tloc}" = "${loc}/data" ]]
					then
						echo "${name}"
						exit
					#else
					#	errcho "${tloc} vs ${loc}/data"
					fi 	
				fi
			done
			# if I am here that means we did not found a name useable
			read -r name < "${loc}/name"
			while [[ -e "${name}" ]]
			do
				if [[ -L "${name}" ]]
				then
					tloc=$(readlink "${name}")
					if [[ "${tloc}" = "${blob}" ]]
					then
						echo "${name}"
						exit
					fi 	
				fi
				cnt=$((cnt+1))
				name="${cnt}-${name#*-}"
			done
			echo "${name}"
			exit
		) < "${loc}/name" )
	fi
	if [[ -z "${name}" ]]
	then
		errcho "Got no name at all for ${id} this is a bug, skipping"
		continue
	fi
	if [[ -L "${name}" ]]
	then
		errcho "Name ${name} ${id} is already checked out, continue"
		# nothing left to do, skip it
	else
		ln -s "${blob}" "${name}"
	fi
	echo "${name}"
done

