#!/bin/bash
##########################################################
# Performs some sort of full text search.                #
# it passes all its options to grep -q ... textdata      # 
# if grep does not match, the data is filtered           #
##########################################################
while read id
do
	loc="${IDX_DIR}"/$(idxpand ${id})
	idxchkloc "${loc}" || continue

	if [[ ! -a ${loc}/text ]]
	then 
		errcho "there no text file for ${id} skipping"
		continue
	fi
	grep -q "${@}" "${loc}/text" && echo "${id}"
done

