#!/bin/bash
########################################################
# This one sets an info to a file like a tag or a name #
filter_regex="true"
if [[ ${1} == "-e" ]]
then
	filter_regex="true"
	shift
fi
name=${1}
shift
while read -r id
do
	loc="${IDX_DIR}"/$(idxpand "${id}")
	
	idxchkloc "${loc}" || continue

	if [[ ! -f ${loc}/${name} ]]
	then 
		# we dont have to check if there are no tags 
		continue
	else
		( 
			declare -A temp
			
			if [[ "${filter_regex}" = "true" ]]
			then 
				# we have to compare bit by bit 
				# if we do filtering 
				while read -r s
				do 
					for p in "${@}"
					do
						# shellcheck disable=SC2053
						if [[ "${s}" = ${p} ]]
						then
							echo "${id}"
							exit 
						fi
					done
				done

			else
				# filter_regex implementation 
				for s in "${@}"
				do
					((temp["${s}"]++))
				done
				
				while read -r s
				do 
					if [[ -n "${temp[${s}]}" ]]
					then
						echo "${id}"
						exit 
					fi
				done
			fi
		) < "${loc}/${name}" 
	fi
done

