#!/bin/bash
shopt -s expand_aliases
########################ä#################################
# This creates a text file right next to a data file for #
# full text pdf search                                   #
##########################################################
while read id
do
	gen_loc
	test_loc
	if [[ ! -a ${loc}/data ]]
	then 
		errcho "there is no data file for ${id} skipping"
		continue
	fi
	read mimetype < ${loc}/mimetype
	mimetype=${mimetype:="pdf"}
	case mimetype in
		*pdf*)
			pdftotext ${loc}/data ${loc}/text
		;;
		*)
			errcho "unknown mimetype ${mimetype} for id ${id} skipping"
			continue
		;; 
	esac
	echo ${id}
done

