#!/bin/bash
shopt -s expand_aliases
#################################################
# picks an idx id out of a checked out filename #
while read file
do
	if [[ ! -f ${file} ]]
	then
		errcho "File ${file} does not exist skipping"
		continue
	fi
	if [[ -L ${file} ]]
	then
		link=$(readlink "${file}")
		if [[ ${link} = */data ]]
		then
			id=${link%/data}
			id=${id##*/}
		else
			errcho "File ${file} is a symlink but not pointing to idx store, skipping"
			continue
		fi
	else
		# regular file, not indexed yet 
		errcho "File ${file} is not indexed, skipping"
		continue
	fi
	
	echo ${id}
done

