#!/bin/bash
########################################################
# This one sets an info to a file like a tag or a name #
alias errcho='>&2 echo'
name=${1}
shift
while read id
do
	loc=${HOME}/.idx_data/${id}
	if [[ ! -d ${loc} ]]
	then
		errcho "ID ${id} is not indexed, skipping!"
		continue
	fi
	if [[ ! -f ${loc}/${name} ]]
	then 
		# we dont have to check if there are no tags 
		continue
	else
		( 
			declare -A temp
			
			t="false"

			for s in "${@}"
			do
				((temp[${s}]++))
			done

			while read s
			do 
				if [[ -n "${temp[${s}]}" ]]
				then
					t="true"
				fi
			done
			if [[ "${t}" = "true" ]]
			then
				echo ${id}
			fi
		) < ${loc}/${name} 
	fi
done

